### ISSUE TITLE
Whitout Image - Main Page

### ISSUE THREAD

**Issue by MxJesusDiaz** [hugmanrique/PlayManagerPublic#17]
The server **FantasyCraft** in the main page not contain image (logo).
[https://i.imgur.com/o596uld.jpg](url)

Thanks for your attention. ^^

**Comment by hugmanrique** [comment]
Thank you for your report! The PlayManager page will most likely suffer a complete recode with HugStrap, my new CSS framework and as so I will try to tweak and squash all those persky bugs that currently there are.

**Comment by hugmanrique** [comment]
This is fixed right now, but won't be available until the new PlayManager's website release
